; ============================
; PHP config
; ============================

; File uploads
upload_max_filesize = 100M
post_max_size = 100M

; Memory and execution
memory_limit = 512M
max_execution_time = 300
max_input_time = 300

; Errors — скрываем от пользователя, пишем в лог
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /dev/stderr
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

; Security
expose_php = Off

; Date/Time
date.timezone = Asia/Tashkent
